# Generated by Django 4.0 on 2021-12-26 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('player_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.png', null=True, upload_to='profile_pics')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
