# Generated by Django 4.0 on 2021-12-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='session_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
