# Generated by Django 4.0 on 2022-01-07 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='player_id',
            field=models.UUIDField(default=uuid.UUID('f32e8302-0651-401b-9e74-b9a649dca2e7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
