# Generated by Django 4.0 on 2021-12-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_created_profile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
    ]
