# Generated by Django 4.0 on 2022-01-08 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='player_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sanitized_name',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
    ]
