# Generated by Django 4.0 on 2022-01-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_player_id_alter_profile_sanitized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sanitized_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
