version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/chess
    ports:
      - 8000:8000
    image: app:chess
    container_name: chess_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/
    environment:
      - POSTFRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
