# Generated by Django 4.0 on 2021-12-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='openGame',
            field=models.BooleanField(default=True),
        ),
    ]
