# Generated by Django 4.0 on 2021-12-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
        ('chess_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='white',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='users.profile'),
        ),
    ]
